// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8iT2Jc1gIxvihl1LlCuawyAd6x4FEnwo',
    appId: '1:486680353564:web:4f186a595928bf5db1b8d9',
    messagingSenderId: '486680353564',
    projectId: 'pharmacy-app-ef43f',
    authDomain: 'pharmacy-app-ef43f.firebaseapp.com',
    storageBucket: 'pharmacy-app-ef43f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7Zhj7dK9jTSqkfraBseC9c7SAheIUus0',
    appId: '1:486680353564:android:a586fc0e5d611d39b1b8d9',
    messagingSenderId: '486680353564',
    projectId: 'pharmacy-app-ef43f',
    storageBucket: 'pharmacy-app-ef43f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMITp0KwovzkMyxwvq4r5kyI8inRvgMMQ',
    appId: '1:486680353564:ios:bc15651b61b8ced6b1b8d9',
    messagingSenderId: '486680353564',
    projectId: 'pharmacy-app-ef43f',
    storageBucket: 'pharmacy-app-ef43f.firebasestorage.app',
    iosBundleId: 'com.example.pharmacyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMITp0KwovzkMyxwvq4r5kyI8inRvgMMQ',
    appId: '1:486680353564:ios:bc15651b61b8ced6b1b8d9',
    messagingSenderId: '486680353564',
    projectId: 'pharmacy-app-ef43f',
    storageBucket: 'pharmacy-app-ef43f.firebasestorage.app',
    iosBundleId: 'com.example.pharmacyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8iT2Jc1gIxvihl1LlCuawyAd6x4FEnwo',
    appId: '1:486680353564:web:8110155d9d01f82db1b8d9',
    messagingSenderId: '486680353564',
    projectId: 'pharmacy-app-ef43f',
    authDomain: 'pharmacy-app-ef43f.firebaseapp.com',
    storageBucket: 'pharmacy-app-ef43f.firebasestorage.app',
  );
}
